version: '3.7'
services:
  mysql:
    image: mysql:5.7
    env_file:
      - ./symfony/.env
    environment:
      - MYSQL_ROOT_PASSWORD="${DB_ROOT_PASSWORD}"
      - MYSQL_DATABASE="${DB_DATABASE}"
      - MYSQL_USER=symfony
      - MYSQL_PASSWORD=password
  php:
    build: ./docker/php
    links:
      - mysql
    volumes:
      - ./symfony/:/var/www/symfony:cached
  nginx:
    build: ./docker/nginx
    links:
      - php
    volumes:
      - ./logs/nginx:/var/log/nginx:cached
      - ./symfony/:/var/www/symfony:cached
